### ISSUE TITLE
Config option 'host' does not accept hostname, only IP

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle-opentsdb-adapter#11]
Despite the README listing `"host": "hostname"` in the config object, the code only accepts an IP address, not a hostname. With this config:

```
        "opentsdb": {
            "host": "docker-local",
            "port": 4242
        }
```

When I tried reading from opentsdb, it errored out:

```
juttle> read opentsdb -from :0:
[2016-02-11 22:35:23.322] [ERROR] juttle-adapter - error loading adapter [object Object]: host()::invalid input argument. URL is not valid. Ensure valid IP or `localhost`.
Error: host()::invalid input argument. URL is not valid. Ensure valid IP or `localhost`.
Unhandled rejection Error: host()::invalid input argument. URL is not valid. Ensure valid IP or `localhost`.
    at Client.host (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/opentsdb-client/lib/index.js:100:10)
    at Object.DB.init (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle-opentsdb-adapter/lib/db.js:12:20)
    at OpentsdbAdapter (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle-opentsdb-adapter/index.js:7:8)
    at loadAdapter (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/lib/runtime/adapters.js:118:23)
... (stack trace goes on)
```

Works fine with `"host": "192.168.99.100"` in the config. (To be clear, I have this entry in /etc/hosts so the hostname resolves just fine: `192.168.99.100    docker-local`.)

**Comment by dmehra** [comment]
https://github.com/juttle/juttle-opentsdb-adapter/pull/22
The README update changes the doc from "hostname" to "IP address" to reflect reality for now; can change back if/when the bug gets fixed.

**Comment by VladVega** [comment]
Yeah - would need to change the driver which checks for valid ip: https://github.com/opentsdb-js/client/blob/master/lib/index.js#L98
